### ISSUE TITLE
Small question

### ISSUE THREAD

**Issue by havenchyk** [elsom25/angular-requirejs-html5boilerplate-seed#5]
Hi, I haven't idea, is it a good place to ask, but I can't find solution in google, so will ask here. 

Is requirejs + angular still good solution? 
I want to use they together, but for production imho the best solution is to use r.js optimizer and single js file. So what's benefits of using angularjs with requirejs together today?

Thanks in advance. 
Vladimir

**Comment by elsom25** [comment]
you shouldn't use them together anymore, as angularjs provides it's own dependency manager.

**Comment by havenchyk** [comment]
Thanks for quick respoince and your help. Could you get link to docs or any post to understand, why I shouldn't use them together?

**Comment by elsom25** [comment]
it's just not really beneficial to use them together anymore (imo). At least for the use cases I was using it for, I find Angular's dependency injection to be sufficient.

I've done a toy project before setting it up, and recall it being fairly straightforward, but, that was over a year ago, so I don't recall how to do it off the top of my head.

A stackoverflow with an example of setting up extern libraries: http://stackoverflow.com/a/19156481/192196

**Comment by havenchyk** [comment]
thanks for explanation
